Merged trunk with upstream (postgis-1.1.3).

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -309,7 +309,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CXX CXXFLAGS ac_ct_CXX LN_S USE_ICONV ICONV_LDFLAGS CPP EGREP build build_cpu build_vendor build_os host host_cpu host_vendor host_os PGCONFIG PGFEINCLUDES PGBEINCLUDES PGFELIBS PGBELIBS PGBIN PGTEMPLATE LPATH USE_GEOS GEOS_DIR USE_GEOS_CAPI GEOSCONFIG USE_PROJ PROJ_DIR PROJ USE_JTS JTS_INCLUDES JTS_LIBDIR JTSCONFIG FLEX DLLWRAP DLLTOOL YACC INSTALL PERL docdir XSLBASE XSLTPROC PDFXMLTEX JW DOC_RULE PORTNAME DLSUFFIX DLFLAGS EXE HOST_OS ELF_SYS LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CXX CXXFLAGS ac_ct_CXX LN_S USE_ICONV ICONV_LDFLAGS CPP EGREP build build_cpu build_vendor build_os host host_cpu host_vendor host_os PGCONFIG PGFEINCLUDES PGBEINCLUDES PGFELIBS PGBELIBS PGBIN PGTEMPLATE LPATH PWDREGRESS USE_GEOS GEOS_DIR GEOS_LDFLAGS USE_GEOS_CAPI GEOSCONFIG USE_PROJ PROJ_DIR PROJ_LIBDIR PROJ USE_JTS JTS_INCLUDES JTS_LIBDIR JTSCONFIG FLEX DLLWRAP DLLTOOL YACC INSTALL PERL docdir XSLBASE XSLTPROC PDFXMLTEX DB2PDF JW DOC_RULE PORTNAME DLSUFFIX DLFLAGS EXE HOST_OS ELF_SYS LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -857,7 +857,10 @@ Optional Packages:
                           [ARG=path to pg_config]
   --with-geos[=ARG]       enable spatial predicates and operators using GEOS
                           [ARG=path to geos-config]
+  --with-geos-libdir=PATH path to GEOS libdir
+                          [taken from geos-config by default]
   --with-proj[=DIR]       enable reprojection support
+  --with-proj-libdir=PATH path to PROJ4 libdir
   --with-jts[=ARG]        use JTS for spatial predicates and operators
                           [ARG=path to jts-config]
   --with-docdir=DIR       install the documentation in DIR [PREFIX/share/doc]
@@ -2697,6 +2700,75 @@ if test $ac_cv_lib_iconv_iconv_open = yes; then
 		ICONV_LDFLAGS=-liconv
 
 else
+  echo "$as_me:$LINENO: checking for libiconv_open in -liconv" >&5
+echo $ECHO_N "checking for libiconv_open in -liconv... $ECHO_C" >&6
+if test "${ac_cv_lib_iconv_libiconv_open+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-liconv  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char libiconv_open ();
+int
+main ()
+{
+libiconv_open ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_iconv_libiconv_open=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_iconv_libiconv_open=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_iconv_libiconv_open" >&5
+echo "${ECHO_T}$ac_cv_lib_iconv_libiconv_open" >&6
+if test $ac_cv_lib_iconv_libiconv_open = yes; then
+  USE_ICONV=1
+			ICONV_LDFLAGS=-liconv
+
+else
   echo "$as_me:$LINENO: checking for iconv_open in -lc" >&5
 echo $ECHO_N "checking for iconv_open in -lc... $ECHO_C" >&6
 if test "${ac_cv_lib_c_iconv_open+set}" = set; then
@@ -2767,6 +2839,9 @@ if test $ac_cv_lib_c_iconv_open = yes; then
 
 else
   USE_ICONV=0
+
+fi
+
 
 fi
 
@@ -3566,10 +3641,24 @@ fi
 
 
 PGFEINCLUDES="-I"`${PGCONFIG} --includedir`
-PGFELIBS="-L"`${PGCONFIG} --libdir`" -lpq "`${PGCONFIG} --libs 2> /dev/null`
+PGFELIBS="-L"`${PGCONFIG} --libdir`" -lpq " #(1)# `${PGCONFIG} --libs 2> /dev/null`
+#(1)#
+# We don't really want to link to more libs then required, see:
+# http://postgis.refractions.net/pipermail/postgis-devel/2006-May/002124.html
 PGBELIBS="-L"`${PGCONFIG} --libdir`" -lpostgres"
 PGBEINCLUDES="-I"`${PGCONFIG} --includedir-server`
 PGBIN=`${PGCONFIG} --bindir`
+
+case $host_os in
+	*mingw*)
+		PWDREGRESS="pwd -W"
+		;;
+	*)
+		PWDREGRESS="pwd"
+		;;
+esac
+
+
 
 
 
@@ -3578,6 +3667,7 @@ PGBIN=`${PGCONFIG} --bindir`
 USE_GEOS=0
 USE_GEOS_CAPI=0
 GEOS_DIR=
+GEOS_LDFLAGS=
 
 # Extract the first word of "geos-config", so it can be a program name with args.
 set dummy geos-config; ac_word=$2
@@ -3645,6 +3735,7 @@ fi;
 
 if test $USE_GEOS -gt 0; then
 	GEOS_DIR=`$GEOSCONFIG --prefix`
+	GEOS_LDFLAGS=`$GEOSCONFIG --ldflags`
 	GEOS_MAJOR=`$GEOSCONFIG --version | cut -d. -f1`
 	if test "$GEOS_MAJOR" = "@GEOS_VERSION@"; then
 		GEOS_MAJOR=1
@@ -3660,10 +3751,32 @@ if test $USE_GEOS -gt 0; then
 fi
 
 
+# Check whether --with-geos-libdir or --without-geos-libdir was given.
+if test "${with_geos_libdir+set}" = set; then
+  withval="$with_geos_libdir"
+
+case "$with_geos_libdir" in
+	no|yes)
+		{ { echo "$as_me:$LINENO: error: Invalid argument to --with-geos-libdir" >&5
+echo "$as_me: error: Invalid argument to --with-geos-libdir" >&2;}
+   { (exit 1); exit 1; }; }
+		;;
+	*)
+		GEOS_LDFLAGS=-L${with_geos_libdir}
+		;;
+esac
+
+else
+  with_geos_libdir=no
+fi;
+
+
+
 
 
 USE_PROJ=0
 PROJ_DIR=
+PROJ_LIBDIR=
 # Extract the first word of "proj", so it can be a program name with args.
 set dummy proj; ac_word=$2
 echo "$as_me:$LINENO: checking for $ac_word" >&5
@@ -3728,7 +3841,28 @@ if test $USE_PROJ -gt 0; then
 echo "$as_me: error: Can't find proj dir." >&2;}
    { (exit 1); exit 1; }; };
 	fi
+	PROJ_LIBDIR=${PROJ_DIR}/lib
 fi
+
+
+# Check whether --with-proj-libdir or --without-proj-libdir was given.
+if test "${with_proj_libdir+set}" = set; then
+  withval="$with_proj_libdir"
+
+case "$with_proj_libdir" in
+	no|yes)
+		{ { echo "$as_me:$LINENO: error: Invalid argument to --with-proj-libdir" >&5
+echo "$as_me: error: Invalid argument to --with-proj-libdir" >&2;}
+   { (exit 1); exit 1; }; }
+		;;
+	*)
+		PROJ_LIBDIR=${with_proj_libdir}
+		;;
+esac
+
+else
+  with_proj_libdir=no
+fi;
 
 
 
@@ -3932,38 +4066,35 @@ echo "${ECHO_T}no" >&6
 fi
 
 
-
-# Extract the first word of "yacc", so it can be a program name with args.
-set dummy yacc; ac_word=$2
+for ac_prog in 'bison -y' byacc
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
 echo "$as_me:$LINENO: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
-if test "${ac_cv_path_YACC+set}" = set; then
+if test "${ac_cv_prog_YACC+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
-  case $YACC in
-  [\\/]* | ?:[\\/]*)
-  ac_cv_path_YACC="$YACC" # Let the user override the test with a path.
-  ;;
-  *)
-  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+  if test -n "$YACC"; then
+  ac_cv_prog_YACC="$YACC" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
 for as_dir in $PATH
 do
   IFS=$as_save_IFS
   test -z "$as_dir" && as_dir=.
   for ac_exec_ext in '' $ac_executable_extensions; do
   if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
-    ac_cv_path_YACC="$as_dir/$ac_word$ac_exec_ext"
+    ac_cv_prog_YACC="$ac_prog"
     echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
     break 2
   fi
 done
 done
 
-  ;;
-esac
 fi
-YACC=$ac_cv_path_YACC
-
+fi
+YACC=$ac_cv_prog_YACC
 if test -n "$YACC"; then
   echo "$as_me:$LINENO: result: $YACC" >&5
 echo "${ECHO_T}$YACC" >&6
@@ -3971,6 +4102,10 @@ else
   echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
+
+  test -n "$YACC" && break
+done
+test -n "$YACC" || YACC="yacc"
 
 if test -z "$YACC"; then
 	{ { echo "$as_me:$LINENO: error: Can't find 'yacc'" >&5
@@ -4131,6 +4266,45 @@ PDFXMLTEX=$ac_cv_path_PDFXMLTEX
 if test -n "$PDFXMLTEX"; then
   echo "$as_me:$LINENO: result: $PDFXMLTEX" >&5
 echo "${ECHO_T}$PDFXMLTEX" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+# Extract the first word of "db2pdf", so it can be a program name with args.
+set dummy db2pdf; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_DB2PDF+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $DB2PDF in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_DB2PDF="$DB2PDF" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_DB2PDF="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  ;;
+esac
+fi
+DB2PDF=$ac_cv_path_DB2PDF
+
+if test -n "$DB2PDF"; then
+  echo "$as_me:$LINENO: result: $DB2PDF" >&5
+echo "${ECHO_T}$DB2PDF" >&6
 else
   echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6
@@ -5082,12 +5256,15 @@ s,@PGBELIBS@,$PGBELIBS,;t t
 s,@PGBIN@,$PGBIN,;t t
 s,@PGTEMPLATE@,$PGTEMPLATE,;t t
 s,@LPATH@,$LPATH,;t t
+s,@PWDREGRESS@,$PWDREGRESS,;t t
 s,@USE_GEOS@,$USE_GEOS,;t t
 s,@GEOS_DIR@,$GEOS_DIR,;t t
+s,@GEOS_LDFLAGS@,$GEOS_LDFLAGS,;t t
 s,@USE_GEOS_CAPI@,$USE_GEOS_CAPI,;t t
 s,@GEOSCONFIG@,$GEOSCONFIG,;t t
 s,@USE_PROJ@,$USE_PROJ,;t t
 s,@PROJ_DIR@,$PROJ_DIR,;t t
+s,@PROJ_LIBDIR@,$PROJ_LIBDIR,;t t
 s,@PROJ@,$PROJ,;t t
 s,@USE_JTS@,$USE_JTS,;t t
 s,@JTS_INCLUDES@,$JTS_INCLUDES,;t t
@@ -5103,6 +5280,7 @@ s,@docdir@,$docdir,;t t
 s,@XSLBASE@,$XSLBASE,;t t
 s,@XSLTPROC@,$XSLTPROC,;t t
 s,@PDFXMLTEX@,$PDFXMLTEX,;t t
+s,@DB2PDF@,$DB2PDF,;t t
 s,@JW@,$JW,;t t
 s,@DOC_RULE@,$DOC_RULE,;t t
 s,@PORTNAME@,$PORTNAME,;t t
@@ -5627,10 +5805,12 @@ echo "${ECHO_T}    GEOS: $GEOSCONFIG (with C-API)" >&6
 		echo "$as_me:$LINENO: result:     GEOS: $GEOSCONFIG" >&5
 echo "${ECHO_T}    GEOS: $GEOSCONFIG" >&6
 	fi
+        echo "$as_me:$LINENO: result:           (ldflags: $GEOS_LDFLAGS)" >&5
+echo "${ECHO_T}          (ldflags: $GEOS_LDFLAGS)" >&6
 fi
 if test $USE_PROJ -gt 0; then
-	echo "$as_me:$LINENO: result:     PROJ: dir=$PROJ_DIR" >&5
-echo "${ECHO_T}    PROJ: dir=$PROJ_DIR" >&6
+	echo "$as_me:$LINENO: result:     PROJ: prefix=$PROJ_DIR libdir=$PROJ_LIBDIR" >&5
+echo "${ECHO_T}    PROJ: prefix=$PROJ_DIR libdir=$PROJ_LIBDIR" >&6
 fi
 echo "$as_me:$LINENO: result:    ICONV: $USE_ICONV $ICONV_LDFLAGS" >&5
 echo "${ECHO_T}   ICONV: $USE_ICONV $ICONV_LDFLAGS" >&6
